server:
  port: 8081

spring:
  application:
    name: chat-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
    
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      
  # MySQL 설정 (필요한 경우)
  datasource:
    url: jdbc:mysql://localhost:3306/chat_service?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  # RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    stomp:
      port: 61613
    
  # WebSocket 설정
  websocket:
    path: /ws
    allowed-origins: "*"

# RabbitMQ Exchange 설정
rabbitmq:
  chat-exchange:
    name: "chat.exchange"

# Swagger 설정
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    default-models-expand-depth: -1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# 로깅 설정
logging:
  level:
    root: INFO
    com.homeless.chatservice: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.amqp: DEBUG
